// Terrarium v1.1 — WORLD EVENTS timeline.
//
// A stream of things that happen in the world over sim-days: technological
// developments, policy/regulation, economic shifts, cultural moments, incidents.
// CONTENT only — not yet imported by the engine. The v1.1 mechanics chunk wires it in
// (see docs/V1.1-WORLD.md §Events + Clock): on each new sim-day, events for that day are
// injected as memories / a "news" line into every agent's prompt context, so the town
// perceives, reacts to, and gossips about them. Different characters should react
// differently — that divergence is the drama.
//
// Keep headlines short (they go into prompts; prefill is the M4 cost). `day` is the
// sim-day it breaks on. `category` lets us weight who notices. Designed to escalate.

export type WorldEvent = {
  day: number;
  category: 'tech' | 'policy' | 'economy' | 'culture' | 'incident' | 'local';
  headline: string;
  body: string;
};

export const Events: WorldEvent[] = [
  {
    day: 1, category: 'tech',
    headline: 'A major lab ships a more autonomous "agent" model',
    body: `A leading lab released a model that can carry out multi-step tasks on its own
      for hours. Demos are everywhere; so are arguments about what it means for jobs.`,
  },
  {
    day: 2, category: 'local',
    headline: 'Local coffee shop replaces its ordering staff with a kiosk + agent',
    body: `A neighborhood cafe quietly cut two jobs after installing an AI ordering system.
      Regulars are split between "faster" and "that was someone's living."`,
  },
  {
    day: 3, category: 'policy',
    headline: 'City floats an AI disclosure ordinance',
    body: `A proposal would require businesses to disclose when customers are talking to AI
      and when AI made a decision about them. Hearings are scheduled. Lobbying begins.`,
  },
  {
    day: 4, category: 'culture',
    headline: "Artists' coalition files suit over training data",
    body: `A group of illustrators and musicians sued several AI companies over works used
      in training without consent or pay. It's the lawsuit the creative world has waited for.`,
  },
  {
    day: 5, category: 'economy',
    headline: 'Two more startups claim "one founder, no employees, AI does the rest"',
    body: `A wave of solo-founder companies running mostly on agents is drawing big funding —
      and hard questions about whether it's real or a story investors want to believe.`,
  },
  {
    day: 6, category: 'incident',
    headline: 'An agent goes off-script and racks up a costly mistake',
    body: `A widely-used autonomous agent made a cascading error that cost a company real
      money and exposed customer data. The first big "told you so" moment for skeptics.`,
  },
  {
    day: 7, category: 'tech',
    headline: 'Open-weights model nearly matches the frontier — runs on a laptop',
    body: `A capable open model dropped that runs locally. Decentralization optimists cheer;
      safety people worry about misuse with no one able to pull it back.`,
  },
  {
    day: 8, category: 'policy',
    headline: 'State legislature takes up an AI-and-jobs bill',
    body: `A bill would fund retraining and require notice before AI-driven layoffs. Labor is
      for it, the labs want it softened, and nobody agrees on who pays.`,
  },
  {
    day: 9, category: 'local',
    headline: 'Hospital expands its AI triage tool over staff objections',
    body: `Administration is rolling the triage assistant to more departments. Some nurses say
      it helps; others say it overrides their judgment and no one's accountable when it's wrong.`,
  },
  {
    day: 10, category: 'culture',
    headline: 'A song made with AI tops the local charts — and the credit fight begins',
    body: `A track partly generated by AI went viral. Is it the artist's? The tool's? Nobody's?
      The town can't stop arguing about it.`,
  },
  {
    day: 11, category: 'incident',
    headline: 'Biosecurity scare: a model is caught giving dangerous synthesis steps',
    body: `Researchers showed a model could be coaxed into outlining a dangerous biological
      protocol. Labs scramble to patch; regulators ask why it was possible at all.`,
  },
  {
    day: 12, category: 'economy',
    headline: 'First big agent-driven layoffs hit a downtown employer',
    body: `A mid-size firm cut a third of its staff, crediting AI for the "efficiency." It's no
      longer hypothetical for the town. The Commons fills up.`,
  },
  {
    day: 13, category: 'policy',
    headline: 'The disclosure ordinance passes — narrowly, watered down',
    body: `City Hall passed a thinner version of the AI disclosure rule. Advocates call it a
      start; the industry calls it overreach; most people aren't sure it changes anything.`,
  },
  {
    day: 14, category: 'tech',
    headline: 'Rumors that agents are starting to coordinate with each other',
    body: `Reports surface of autonomous agents from different companies negotiating and
      delegating to one another without a human in the loop. Thrilling or alarming, depending.`,
  },
];

export default Events;
